project:
  type: website
  output-dir: _site

website:
  title: "Artificial Intelligence Policy"
  site-url: https://jacklreilly.github.io/aip_s26/
  repo-url: https://github.com/jacklreilly/aip_s26
  navbar:
    title: "**Artificial Intelligence Policy**"
    right:
      - href: overview.qmd
        text: ğŸ  Overview
      - href: schedule.qmd
        text: ğŸ“… Schedule
      - href: content/index.qmd
        text: ğŸ“š Content
      - href: work/index.qmd
        text: ğŸ“ Work 
      - href: policies.qmd
        text: ğŸ« Policies
      - href: ai.qmd
        text: ğŸ¤– AI & LLMs
      - href: https://blackboard.syr.edu/
        text: ğŸ’» Blackboard
  page-footer:
    left: |
      Â© 2026 Jack Reilly<br>
      [Contact](mailto:jlreilly@syr.edu)
      
    center: |
      
      
    right: |
      Built with [Quarto](https://quarto.org)<br>
      [About](/about.qmd)

  sidebar:
    - id: content
      style: docked
      title: "Content"
      #logo: images/pai600_dwv_logo2.svg
      contents:
        - section: "1. What is AI?"
          href: content/index.qmd
          contents:
          - content/w11.qmd
          - content/w12.qmd
          - content/w21.qmd
          - content/w22.qmd
          - content/w31.qmd
          - content/w32.qmd                    




    - id: work
      style: docked
      title: "Work"
      #logo: images/pai600_dwv_logo2.svg
      contents:
        - section: "Debates"
          href: work/index.qmd
          contents:
          - work/dguidelines.qmd
          - work/dtips.qmd
          - work/d1res.qmd
          - work/d2res.qmd
          - work/d3res.qmd
          - work/d4res.qmd
          - work/d5res.qmd
          - work/d6res.qmd

        - section: "Assignments"
          href: work/index.qmd
          contents:
          - work/assign1.qmd
          - work/assign2.qmd

        - section: "Final Project"
          href: work/final.qmd
          contents:
          - work/final.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
execute:
  freeze: auto



